version: '3'
services:
  web:
    build: .
    command: tail -f /dev/null
#    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/qanda
    ports:
      - "3000:3000"